export const Images = {
  COD1: require("./assets/cod1.jpg") as string,
  COD2: require("./assets/cod2.jpg") as string,
  COD3: require("./assets/cod3.svg").default as string,
  MarketPlace1: require("./assets/marketplace1.jpg") as string,
  MarketPlace2: require("./assets/marketplace2.svg").default as string,
  Wallet1: require("./assets/wallet1.svg").default as string,
  Wallet2: require("./assets/wallet2.jpg") as string,
  Wallet3: require("./assets/wallet3.jpg") as string,
  Wallet4: require("./assets/wallet4.jpg") as string,
	Creation1: require("./assets/creation1.jpg") as string,
	PlaningCODs1: require("./assets/planingCODs1.jpg") as string,
  Tokenomics1: require("./assets/tokenomics1.jpg") as string,
  Tokenomics2: require("./assets/tokenomics2.jpg") as string,
  Tokenomics3: require("./assets/tokenomics3.jpg") as string,
  Tokenomics4: require("./assets/tokenomics4.jpg") as string,
  Tokenomics5: require("./assets/tokenomics5.jpg") as string,
  Tokenomics6: require("./assets/tokenomics6.jpg") as string,
  Tokenomics7: require("./assets/tokenomics7.jpg") as string,
  Tokenomics8: require("./assets/tokenomics8.jpg") as string,
  Tokenomics9: require("./assets/tokenomics9.jpg") as string,
  Tokenomics10: require("./assets/tokenomics10.jpg") as string,
};